config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'
  resources :plans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
    validates :title, presence:true
    validates :startday, presence:true
    validates :finishday, presence:true
    validate :date_before_finish

    def date_before_finish
        errors.add(:finishday, "は今日以降の日付で選択してください") if finishday.nil? || finishday < Date.today
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end
  
  def new
    @plan = Plan.new
  end
  
  def create
    @plan = Plan.new(params.require(:plan).permit(:title,:startday,:finishday,:allday,:planmemo))
    if @plan.save
      flash[:notice]="予定を新規登録しました"
      redirect_to :plans
    else
      render "new"
    end
  end
  
  def show
    @plan=Plan.find(params[:id])
  end
  
  def edit
    @plan=Plan.find(params[:id])
  end
  
  def update
    @plan=Plan.find(params[:id])
    if @plan.update(params.require(:plan).permit(:title,:startday,:finishday,:allday,:planmemo))
      flash[:notice]="IDが「#{@plan.id}」のスケジュールを更新しました"
      redirect_to:plans
    else
      render "edit"
    end
  end
  
  def destroy
    @plan=Plan.find(params[:id])
    @plan.destroy
    flash[:notice]="スケジュールを削除しました"
    redirect_to:plans
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <div>
      <%= yield %>  
    </div>
    <footer>
      <h1>現在の日時：<%=Time.now.strftime('%Y年%m月%d日')%>　スケジュール合計：<%=Plan.count%></h1>
    </footer>
  </body>
</html>

app/views/plans/edit.html.erb
<h3>スケジュール編集</h3>

<%=render "shared/error",obj:@plan%>

<%=form_with model:@plan do|f|%>
    <table>
        <tr>
            <th><%=f.label:title,"タイトル"%></th>
            <td><%=f.text_field:title%></td>
        </tr>
        <tr>
            <th><%=f.label:startday,"開始日"%></th>
            <td><%=f.date_field:startday%></td>
        </tr>
        <tr>
            <th><%=f.label:finishday,"終了日"%></th>
            <td><%=f.date_field:finishday%></td>
        </tr>
        <tr>
            <th><%=f.label:allday,"終日"%></th>
            <td><%=f.check_box:allday%></td>
        </tr>
        <tr>
            <th><%=f.label:planmemo,"スケジュールメモ"%></th>
            <td><%=f.text_area:planmemo%></td>
        </tr>
    </table>

    <div>
        <ul>
            <li><%=f.submit "スケジュールの編集を完了する"%></li>
            <li><%=link_to "スケジュール一覧に戻る",plans_path%></li>
        </ul>
    </div>
<%end%>

app/views/plans/index.html.erb
<h1>スケジュール一覧</h1>

<% if flash[:notice]%>
    <p class="notice"><%=flash[:notice]%></p>
<%end%>


<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>スケジュール更新日時</th>
            <th>確認</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    
    <tbody>
        <% @plans.each do |plan|%>
            <tr>
                <td><%=plan.id%></td>
                <td><%=plan.title%></td>
                <td><%=plan.startday.strftime('%Y年%m月%d日')%></td>
                <td><%=plan.finishday.strftime('%Y年%m月%d日')%></td>
                <% if plan.allday=='1'%>
                    <td>○</td>
                <% else%>
                    <td></td>
                <%end%>
                <td><%=plan.updated_at.to_s(:datetime_jp)%></td>
                <td><%=link_to"確認",plan_path(plan)%></td>
                <td><%=link_to"編集",edit_plan_path(plan)%></td>
                <td><%=link_to"削除",plan_path(plan),method: :delete,data:{confirm:"本当に削除しますか？"}%></td>
            </tr>
        <%end%>
    </tbody>
</table>

<p><%=link_to "スケジュール新規登録",:new_plan%></p>

app/views/plans/new.html.erb
<h3>スケジュール新規作成</h3>

<% if flash[:notice]%>
    <p class="notice"><%=flash[:notice]%></p>    
<%end%>

<%=render "shared/error",obj:@plan%>

<%=form_with model:@plan do|f|%>
    <table>
        <tr>
            <th><%=f.label:title,"タイトル"%></th>
            <td><%=f.text_field:title%></td>
        </tr>
        <tr>
            <th><%=f.label:startday,"開始日"%></th>
            <td><%=f.date_field:startday%></td>
        </tr>
        <tr>
            <th><%=f.label:finishday,"終了日"%></th>
            <td><%=f.date_field:finishday%></td>
        </tr>
        <tr>
            <th><%=f.label:allday,"終日"%></th>
            <td><%=f.check_box:allday%><p>終日の場合はチェックを入れます</p></td>
        </tr>
        <tr>
            <th><%=f.label:planmemo,"スケジュールメモ"%></th>
            <td><%=f.text_area:planmemo%></td>
        </tr>
    </table>

    <div>
        <ul>
            <li><%=f.submit "スケジュールを新規登録する"%></li>
            <li><%=link_to "スケジュール一覧に戻る",plans_path%></li>
        </ul>
    </div>
<%end%>

app/views/plans/show.html.erb
<h3>スケジュール詳細</h3>

<table>
    <tr>
        <th>タイトル</th>
        <td><%=@plan.title%></td>
    </tr>
    <tr>
        <th>開始日</th>
        <td><%=@plan.startday.strftime('%Y年%m月%d日')%></td>
    </tr>
    <tr>
        <th>終了日</th>
        <td><%=@plan.finishday.strftime('%Y年%m月%d日')%></td>
    </tr>
    <tr>
        <th>終日</th>
        <% if @plan.allday=='1'%>
            <td>○</td>
        <% else%>
            <td></td>
        <%end%>
    </tr>
    <tr>
        <th>スケジュールメモ</th>
        <td><%=@plan.planmemo%></td>
    </tr>
</table>

<div>
    <ul>
        <li><%=link_to "スケジュール一覧に戻る",plans_path%></li>
        <li><%=link_to "スケジュールを編集する",edit_plan_path%></li>
        <li><%=link_to "スケジュールを削除",plan_path,method: :delete,data:{confirm:"本当に削除しますか？"}%></li>
    </ul>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any?%>
    <% obj.errors.full_messages.each do |message|%>
        <ul>
            <li><%=message%></li>
        </ul>
    <%end%>
<%end%>